<?php

namespace App\Http\Controllers\Api;

use App\Exceptions\InsufficientFundsException;
use App\Http\Controllers\Controller;
use App\Models\Transaction;
use App\Models\Wallet;
use App\Services\PaymentConfirmationService;
use App\Services\TransactionService;
use App\Services\VopService;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class TransactionController extends Controller
{
    public function __construct(
        private TransactionService $transactions,
        private VopService $vop,
        private PaymentConfirmationService $confirmations,
    ) {
    }

    /**
     * Return the authenticated user's transactions.
     */
    public function index(Request $request)
    {
        /*
         * The authenticated user must have
         * an AuraPay wallet.
         */
        $wallet = $request->user()->wallet;

        if (! $wallet) {
            return response()->json([
                'message' =>
                    'Wallet not found for authenticated user.',
            ], 404);
        }

        /*
         * Return only transactions where the
         * authenticated user's wallet is either
         * the sender or the receiver.
         */
        $items = Transaction::query()
            ->where(function ($query) use ($wallet) {
                $query
                    ->where(
                        'sender_wallet_id',
                        $wallet->id
                    )
                    ->orWhere(
                        'receiver_wallet_id',
                        $wallet->id
                    );
            })
            ->latest()
            ->paginate(20);

        return response()->json($items);
    }

    /**
     * Direct account-to-account transfer
     * by receiver wallet ID.
     */
    public function sendA2A(Request $request)
    {
        /*
         * =====================================================
         * 1. IDEMPOTENCY KEY
         * =====================================================
         *
         * Every A2A payment must contain an
         * Idempotency-Key HTTP header.
         */

        $idempotencyKey = trim(
            (string) $request->header(
                'Idempotency-Key'
            )
        );

        if ($idempotencyKey === '') {
            return response()->json([
                'message' =>
                    'Idempotency-Key header is required.',
            ], 400);
        }

        /*
         * Prevent excessively long client keys.
         */
        if (strlen($idempotencyKey) > 100) {
            return response()->json([
                'message' =>
                    'Idempotency-Key must be at most 100 characters.',
            ], 422);
        }


        /*
 * Correlation ID is generated by the client
 * and is used only for end-to-end traceability.
 */
$correlationId = trim(
    (string) $request->header(
        'X-Correlation-ID'
    )
);

if ($correlationId === '') {
    return response()->json([
        'message' =>
            'X-Correlation-ID header is required.',
    ], 400);
}

if (! Str::isUuid($correlationId)) {
    return response()->json([
        'message' =>
            'X-Correlation-ID must be a valid UUID.',
    ], 422);
}
        /*
         * =====================================================
         * 2. INPUT VALIDATION
         * =====================================================
         */

        $validated = $request->validate([

            'receiver_wallet_id' => [
                'required',
                'integer',
                'exists:wallets,id',
            ],

            'receiver_name' => [
                'required',
                'string',
                'max:255',
            ],

            'amount' => [
                'required',
                'numeric',
                'decimal:0,2',
                'min:0.01',

                /*
                 * transactions.amount is DECIMAL(15,2),
                 * therefore at most 13 digits may appear
                 * before the decimal point.
                 */
                'max:9999999999999.99',
            ],

            /*
             * STEP 4.6
             *
             * The browser receives this token only after
             * a successful Verification of Payee operation.
             *
             * The token cryptographically binds:
             *
             * - authenticated user
             * - receiver wallet
             * - amount
             * - expiration time
             */
            'confirmation_token' => [
                'required',
                'string',
                'max:4096',
            ],
        ]);


        /*
         * =====================================================
         * 3. RESOLVE SENDER WALLET
         * =====================================================
         */

        $sender = $request->user()->wallet;

        if (! $sender) {
            return response()->json([
                'message' =>
                    'Sender wallet not found.',
            ], 404);
        }


        /*
         * =====================================================
         * 4. RESOLVE RECEIVER WALLET
         * =====================================================
         */

        $receiver = Wallet::with('user')
            ->findOrFail(
                $validated['receiver_wallet_id']
            );


        /*
         * A wallet cannot transfer money
         * to itself.
         */
        if ($sender->id === $receiver->id) {
            return response()->json([
                'message' =>
                    'Cannot send funds to your own wallet.',
            ], 422);
        }


        /*
         * Both wallets must be active.
         */
        if (
            ! $sender->isActive()
            || ! $receiver->isActive()
        ) {
            return response()->json([
                'message' =>
                    'One of the wallets is not active.',
            ], 422);
        }


        /*
         * =====================================================
         * 5. IDEMPOTENT REPLAY CHECK
         * =====================================================
         *
         * Check this before creating a new payment.
         *
         * If the same logical payment has already been
         * processed, return the existing result instead
         * of executing another transfer.
         */

        $existing = Transaction::query()
            ->where(
                'sender_wallet_id',
                $sender->id
            )
            ->where(
                'idempotency_key',
                $idempotencyKey
            )
            ->first();


        if ($existing) {

            /*
             * The same Idempotency-Key may only represent
             * the same receiver and the same amount.
             */

            $sameReceiver =
                (int) $existing->receiver_wallet_id
                ===
                (int) $receiver->id;


            /*
             * Do not compare monetary values using
             * raw floating-point equality.
             *
             * Normalize both values to exactly
             * two decimal positions.
             */
            $existingAmount =
                number_format(
                    (float) $existing->amount,
                    2,
                    '.',
                    ''
                );

            $requestedAmount =
                number_format(
                    (float) $validated['amount'],
                    2,
                    '.',
                    ''
                );

            $sameAmount =
                $existingAmount
                ===
                $requestedAmount;


            if (
                ! $sameReceiver
                || ! $sameAmount
            ) {
                return response()->json([
                    'message' =>
                        'Idempotency-Key was already used for a different payment.',
                ], 409);
            }


            /*
             * Same key + same logical payment.
             *
             * No new financial state is created,
             * therefore return the existing transaction.
             */
            return response()
    ->json(
        $existing,
        200
    )
    ->header(
        'X-Idempotent-Replay',
        'true'
    )
    ->header(
        'X-Correlation-ID',
        $correlationId
    );

        }


        /*
         * =====================================================
         * 6. VERIFICATION OF PAYEE
         * =====================================================
         *
         * Verify the recipient again on the server.
         *
         * Client-side VoP information alone must never
         * be trusted.
         */

        $vopResult = $this->vop->verify(
            $receiver,
            $validated['receiver_name']
        );


        if (
            $vopResult['status'] !== 'match'
        ) {
            return response()->json([
                'message' =>
                    'Payment stopped because VoP did not return an exact match.',

                'vop' =>
                    $vopResult,
            ], 422);
        }


        /*
         * =====================================================
         * 7. DYNAMIC PAYMENT CONFIRMATION
         * =====================================================
         *
         * STEP 4.6
         *
         * Verify that the token issued during the
         * confirmation step still matches:
         *
         * - the currently authenticated user;
         * - the current receiver wallet;
         * - the current amount;
         * - the allowed confirmation lifetime.
         *
         * Changing the amount or receiver after
         * confirmation therefore invalidates the token.
         */

        $confirmationIsValid =
            $this->confirmations->verify(
                $validated[
                    'confirmation_token'
                ],
                $request->user(),
                $receiver,
                (float) $validated['amount']
            );


        if (! $confirmationIsValid) {
            return response()->json([
                'message' =>
                    'Payment confirmation is invalid, expired, or does not match the current recipient and amount. Please verify and confirm the payment again.',
            ], 422);
        }


        /*
         * =====================================================
         * 8. PROCESS NEW PAYMENT
         * =====================================================
         */

        try {

            $transaction =
    $this->transactions->sendA2A(
        $sender,
        $receiver,
        (float) $validated['amount'],
        $idempotencyKey,
        $correlationId
    );

        } catch (
            InsufficientFundsException $e
        ) {

            return response()->json([
                'message' =>
                    $e->getMessage(),
            ], 422);
        }


        /*
         * =====================================================
         * 9. RESPONSE
         * =====================================================
         *
         * High-risk transactions are accepted for
         * review but are not completed.
         */

        $statusCode =
            $transaction->status === 'flagged'
                ? 202
                : 201;


        return response()
    ->json(
        $transaction,
        $statusCode
    )
    ->header(
        'X-Correlation-ID',
        $correlationId
    );
    }
}